#!/usr/bin/env python
"""
This step takes the best model, tagged with the "prod" artifact tag in W&B,
and tests it against the test dataset.
"""
import argparse
import logging
import os
import shutil
import matplotlib.pyplot as plt
import mlflow
import json
import wandb
import pandas as pd
import numpy as np
from mlflow.models import infer_signature
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, FunctionTransformer, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import Pipeline, make_pipeline


logging.basicConfig(level=logging.INFO, format="%(asctime)-15s %(message)s")
logger = logging.getLogger()


def delta_date_feature(dates):
    """
    Given a 2d array containing dates (in any format recognized by pd.to_datetime),
    it returns the delta in days between each date and the most recent date in the
    array.
    """
    date_sanitized = pd.DataFrame(dates).apply(pd.to_datetime)
    return date_sanitized.apply(lambda d: (d.max() - d).dt.days, axis=0).to_numpy()


def go(args):

    run = wandb.init(job_type="train_random_forest")
    run.config.update(args)

    # Fix the random seed for reproducibility
    logger.info("Fetching training dataset from W&B")
    trainval_local_path = run.use_artifact(args.trainval_artifact).file()

    X = pd.read_csv(trainval_local_path)
    y = X.pop("price")  # this removes the column "price" from X and assigns it to y

    logger.info("X.shape: %s", X.shape)

    X_train, X_val, y_train, y_val = train_test_split(
        X,
        y,
        test_size=args.val_size,
        stratify=X[args.stratify_by] if args.stratify_by != "none" else None,
        random_state=args.random_seed,
    )

    logger.info("Preparing sklearn pipeline")

    sk_pipe, processed_features = get_inference_pipeline(args)

    # Then fit it to the X_train, y_train data
    logger.info("Fitting the pipeline")

    # Fit the pipeline
    sk_pipe.fit(X_train, y_train)

    # Compute r2 and MAE
    logger.info("Scoring the model")
    r_squared = sk_pipe.score(X_val, y_val)

    y_pred = sk_pipe.predict(X_val)
    mae = mean_absolute_error(y_val, y_pred)

    logger.info("Score: %.4f", r_squared)
    logger.info("MAE: %.4f", mae)

    logger.info("Exporting model")

    # Save model package in the MLFlow sklearn format
    if os.path.exists("random_forest_dir"):
        shutil.rmtree("random_forest_dir")

    # Infer signature for MLflow model
    signature = infer_signature(X_val, y_pred)

    with mlflow.start_run():
        mlflow.sklearn.log_model(
            sk_pipe,
            artifact_path="model",
            signature=signature,
            input_example=X_val.iloc[:5],
        )
        mlflow.sklearn.save_model(
            sk_pipe,
            "random_forest_dir",
            signature=signature,
            input_example=X_val.iloc[:5],
        )

    artifact = wandb.Artifact(
        args.output_artifact,
        type="model_export",
        description="Trained Random Forest pipeline exported for inference",
        metadata=args.__dict__,
    )
    artifact.add_dir("random_forest_dir")

    run.log_artifact(artifact)

    # Plot feature importance
    fig_feat_imp = plot_feature_importance(sk_pipe, processed_features)

    run.summary["r2"] = r_squared
    run.summary["mae"] = mae

    run.log(
        {
            "feature_importance": wandb.Image(fig_feat_imp),
        }
    )


def plot_feature_importance(pipe, feat_names):
    # We collect the feature importance for all non-nlp features first
    feat_imp = pipe["random_forest"].feature_importances_[: len(feat_names) - 1]
    # For the NLP feature we sum all the TF-IDF importance
    nlp_importance = sum(pipe["random_forest"].feature_importances_[len(feat_names) - 1:])
    feat_imp = np.append(feat_imp, nlp_importance)
    fig_feat_imp, sub_feat_imp = plt.subplots(figsize=(10, 10))
    # idx = np.argsort(feat_imp)[::-1]
    sub_feat_imp.bar(range(feat_imp.shape[0]), feat_imp, color="r", align="center")
    _ = sub_feat_imp.set_xticks(range(feat_imp.shape[0]))
    _ = sub_feat_imp.set_xticklabels(np.array(feat_names), rotation=90)
    fig_feat_imp.tight_layout()
    return fig_feat_imp


def get_inference_pipeline(args):
    # Get the configuration for the random forest
    with open(args.rf_config) as fp:
        rf_config = json.load(fp)

    # We need to impute the missing values for the numerical columns.
    # We will use the median strategy.
    # NOTE: The strategies are:
    # - mean: replace missing values using the mean along each column
    # - median: replace missing values using the median along each column
    # - most_frequent: replace missing using the most frequent value along each column
    # - constant: replace missing values with fill_value
    zero_imputed = [
        "minimum_nights",
        "number_of_reviews",
        "reviews_per_month",
        "calculated_host_listings_count",
        "availability_365",
        "longitude",
        "latitude"
    ]
    zero_imputer = SimpleImputer(strategy="constant", fill_value=0)

    # A simple imputer for the categorical variable "last_review"
    date_imputer = make_pipeline(
        SimpleImputer(strategy="most_frequent"),
        FunctionTransformer(delta_date_feature, check_inverse=False, validate=False)
    )

    # Non-ordinal categorical pre-processing
    non_ordinal_categorical = ["neighbourhood_group"]
    non_ordinal_categorical_preproc = make_pipeline(
        SimpleImputer(strategy="most_frequent"),
        OneHotEncoder()
    )

    # Ordinal categorical pre-processing
    ordinal_categorical = ["room_type"]
    ordinal_categorical_preproc = make_pipeline(
        SimpleImputer(strategy="most_frequent"),
        OrdinalEncoder()
    )

    # Let's add a feature extractor for the "name" column
    name_tfidf = make_pipeline(
        SimpleImputer(strategy="constant", fill_value=""),
        FunctionTransformer(lambda x: x.squeeze(), check_inverse=False),
        TfidfVectorizer(
            binary=False,
            max_features=args.max_tfidf_features,
            stop_words="english"
        ),
    )

    # Build ColumnTransformer
    preprocessor = ColumnTransformer(
        transformers=[
            ("zero_imputer", zero_imputer, zero_imputed),
            ("date_features", date_imputer, ["last_review"]),
            ("non_ordinal_cat", non_ordinal_categorical_preproc, non_ordinal_categorical),
            ("ordinal_cat", ordinal_categorical_preproc, ordinal_categorical),
            ("name_tfidf", name_tfidf, ["name"]),
        ],
        remainder="drop",
    )

    processed_features = zero_imputed + ["last_review"] + non_ordinal_categorical + ordinal_categorical + ["name"]

    # Create the inference pipeline
    sk_pipe = make_pipeline(
        preprocessor,
        RandomForestRegressor(**rf_config)
    )

    return sk_pipe, processed_features


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Train a Random Forest")

    parser.add_argument(
        "--trainval_artifact",
        type=str,
        help="Artifact containing the training dataset. It will be split into train and validation.",
        required=True,
    )

    parser.add_argument(
        "--val_size",
        type=float,
        help="Size of the validation split. Fraction of the dataset, or number of items",
        default=0.2,
    )

    parser.add_argument(
        "--random_seed",
        type=int,
        help="Seed for random number generator",
        default=42,
        required=False,
    )

    parser.add_argument(
        "--stratify_by",
        type=str,
        help="Column to use for stratification",
        default="none",
        required=False,
    )

    parser.add_argument(
        "--rf_config",
        help="Random forest configuration. A JSON dict that will be passed to the "
             "scikit-learn constructor for RandomForestRegressor.",
        default="{}",
    )

    parser.add_argument(
        "--max_tfidf_features",
        help="Maximum number of words to consider for the TFIDF",
        default=10,
        type=int,
    )

    parser.add_argument(
        "--output_artifact",
        type=str,
        help="Name for the output serialized model",
        required=True,
    )

    args = parser.parse_args()

    go(args)
