#!/usr/bin/env python
"""
Download from W&B the raw dataset and apply some basic data cleaning,
exporting the result to a new artifact.
"""
import argparse
import logging
import wandb
import pandas as pd


logging.basicConfig(level=logging.INFO, format="%(asctime)-15s %(message)s")
logger = logging.getLogger()


def go(args):

    run = wandb.init(job_type="basic_cleaning")
    run.config.update(args)

    # Download input artifact. This will also log that this script is using this
    # particular version of the artifact
    logger.info("Downloading artifact %s", args.input_artifact)
    artifact_local_path = run.use_artifact(args.input_artifact).file()

    df = pd.read_csv(artifact_local_path)

    # Basic cleaning
    logger.info("Removing duplicate rows")
    df = df.drop_duplicates()

    logger.info("Dropping rows with missing price")
    df = df.dropna(subset=["price"])

    logger.info("Filtering price between %s and %s", args.min_price, args.max_price)
    df = df[df["price"].between(args.min_price, args.max_price)]

    # Filter rows to NYC geographical boundaries
    logger.info("Filtering rows to NYC geographical boundaries")
    idx = df['longitude'].between(-74.25, -73.50) & df['latitude'].between(40.5, 41.2)
    df = df[idx].copy()

    # Convert last_review to datetime
    logger.info("Converting last_review to datetime")
    df['last_review'] = pd.to_datetime(df['last_review'])

    logger.info("Cleaned data has %s rows and %s columns", *df.shape)

    # Save the cleaned data
    df.to_csv("clean_sample.csv", index=False)

    artifact = wandb.Artifact(
        args.output_name,
        type=args.output_type,
        description=args.output_description,
    )
    artifact.add_file("clean_sample.csv")
    run.log_artifact(artifact)

    artifact.wait()


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="A very basic data cleaning")

    parser.add_argument(
        "--input_artifact",
        type=str,
        help="Fully-qualified name for the input artifact",
        required=True
    )

    parser.add_argument(
        "--output_name",
        type=str,
        help="Name for the output artifact",
        required=True
    )

    parser.add_argument(
        "--output_type",
        type=str,
        help="Type for the output artifact",
        required=True
    )

    parser.add_argument(
        "--output_description",
        type=str,
        help="Description for the output artifact",
        required=True
    )

    parser.add_argument(
        "--min_price",
        type=float,
        help="Minimum nightly rental price to include in the dataset",
        required=True
    )

    parser.add_argument(
        "--max_price",
        type=float,
        help="Maximum nightly rental price to include in the dataset",
        required=True
    )

    args = parser.parse_args()

    go(args)
